/*
 * megadotnet 使用Swagger2 构建RESTful API
 *
 * megadotnet  https://github.com/megadotnet/
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserDto struct {
	Activated bool `json:"activated,omitempty"`
	Authorities []string `json:"authorities,omitempty"`
	Email string `json:"email,omitempty"`
	// First Name
	FirstName string `json:"firstName,omitempty"`
	Id int64 `json:"id,omitempty"`
	ImageUrl string `json:"imageUrl,omitempty"`
	LangKey string `json:"langKey,omitempty"`
	LastName string `json:"lastName,omitempty"`
	Login string `json:"login,omitempty"`
}
