/*
 * megadotnet 使用Swagger2 构建RESTful API
 *
 * megadotnet  https://github.com/megadotnet/
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type KeyAndPasswordVm struct {
	Key string `json:"key,omitempty"`
	NewPassword string `json:"newPassword,omitempty"`
}
