/*
 * megadotnet 使用Swagger2 构建RESTful API
 *
 * megadotnet  https://github.com/megadotnet/
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 * ResponseEntity
 * https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/RequestEntity.html
 */

package swagger

type ResponseEntity struct {
	Body interface{} `json:"body,omitempty"`
	StatusCode string `json:"statusCode,omitempty"`
	StatusCodeValue int32 `json:"statusCodeValue,omitempty"`
}
